"""
F&O bhavcopy features: open interest, PCR, basis, implied volatility.

Every test here runs OFFLINE against a synthetic bhavcopy frame. The
loader's network path is exercised separately by hand; pinning it in the
suite would make the suite depend on NSE being reachable and on today
being a trading day, which is how a test file stops being run.

The IV tests matter most. An implied-vol inversion that is subtly wrong
produces plausible numbers - 0.18, 0.24 - that are simply not the market's
volatility, and nothing downstream can tell. So it is pinned against
Black-Scholes round-trips and against the boundary cases where a naive
solver silently returns a bound instead of admitting there is no answer.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from nightevolver.derivatives import (
    FEATURE_NAMES, bs_price, day_features, implied_vol, parse_fo,
)

TRAD = pd.Timestamp("2026-08-20")
NEAR = pd.Timestamp("2026-08-25")
NEXT = pd.Timestamp("2026-09-29")


def fo_frame(symbol="RELIANCE", spot=1000.0, vol=0.25, next_vol=0.28,
             call_oi=1000, put_oi=2000, fut_oi=5000, doi=500,
             fut_px=None, strikes=(0.90, 0.95, 1.00, 1.05, 1.10)):
    """A synthetic F&O day priced with a KNOWN volatility.

    Option prices are generated by Black-Scholes at `vol`, so inverting
    them must return `vol`. That closes the loop: a test using made-up
    prices could only check that IV is finite, not that it is right.
    """
    rows = []
    fut_px = fut_px if fut_px is not None else spot * 1.002
    rows.append(dict(TradDt=TRAD, FinInstrmTp="STF", TckrSymb=symbol,
                     XpryDt=NEAR, StrkPric=np.nan, OptnTp="",
                     ClsPric=fut_px, SttlmPric=fut_px, UndrlygPric=spot,
                     OpnIntrst=fut_oi, ChngInOpnIntrst=doi, TtlTradgVol=10000))
    for xp, v in ((NEAR, vol), (NEXT, next_vol)):
        t = max((xp - TRAD).days, 1) / 365.0
        for m in strikes:
            k = spot * m
            for tp, is_call in (("CE", True), ("PE", False)):
                px = bs_price(spot, k, t, v, is_call)
                rows.append(dict(
                    TradDt=TRAD, FinInstrmTp="STO", TckrSymb=symbol,
                    XpryDt=xp, StrkPric=k, OptnTp=tp,
                    ClsPric=px, SttlmPric=px, UndrlygPric=spot,
                    OpnIntrst=(call_oi if is_call else put_oi),
                    ChngInOpnIntrst=0,
                    TtlTradgVol=(call_oi if is_call else put_oi)))
    return pd.DataFrame(rows)


class TestBlackScholesInversion:
    @pytest.mark.parametrize("vol", [0.10, 0.20, 0.35, 0.60, 1.20])
    @pytest.mark.parametrize("is_call", [True, False])
    def test_round_trip_recovers_the_input_vol(self, vol, is_call):
        px = bs_price(1000, 1000, 0.25, vol, is_call)
        assert implied_vol(px, 1000, 1000, 0.25, is_call) == pytest.approx(vol, abs=1e-3)

    @pytest.mark.parametrize("moneyness", [0.85, 0.95, 1.0, 1.05, 1.15])
    def test_round_trip_away_from_the_money(self, moneyness):
        k = 1000 * moneyness
        px = bs_price(1000, k, 0.10, 0.30, True)
        got = implied_vol(px, 1000, k, 0.10, True)
        assert got == pytest.approx(0.30, abs=5e-3)

    def test_put_call_parity_holds(self):
        c = bs_price(1000, 1000, 0.25, 0.3, True)
        p = bs_price(1000, 1000, 0.25, 0.3, False)
        import math
        assert c - p == pytest.approx(1000 - 1000 * math.exp(-0.065 * 0.25), abs=1e-6)

    def test_a_price_below_intrinsic_is_nan_not_a_bound(self):
        """A stale quote under intrinsic has NO implied vol. Returning
        the lower bound would enter the dataset as a real observation of
        near-zero volatility."""
        assert np.isnan(implied_vol(1.0, 1000, 900, 0.25, True))

    def test_a_price_above_the_no_arbitrage_cap_is_nan(self):
        assert np.isnan(implied_vol(1500.0, 1000, 900, 0.25, True))

    def test_degenerate_inputs_are_nan(self):
        assert np.isnan(implied_vol(10, 1000, 1000, 0.0, True))     # expired
        assert np.isnan(implied_vol(0, 1000, 1000, 0.25, True))     # no price
        assert np.isnan(implied_vol(10, 0, 1000, 0.25, True))       # no spot
        assert np.isnan(implied_vol(float("nan"), 1000, 1000, .25, True))

    def test_it_never_diverges_on_deep_otm(self):
        """Vega collapses far out of the money; Newton diverges there.
        Bisection must return NaN or a real root, never inf/huge."""
        px = bs_price(1000, 2000, 0.02, 0.30, True)
        got = implied_vol(px, 1000, 2000, 0.02, True)
        assert np.isnan(got) or 0.0 < got < 5.0


class TestDayFeatures:
    def test_recovers_the_volatility_the_options_were_priced_at(self):
        f = day_features(fo_frame(vol=0.25), ["RELIANCE"])
        assert f.at["RELIANCE", "atm_iv"] == pytest.approx(0.25, abs=0.01)

    def test_flat_smile_gives_zero_skew(self):
        """Same vol at every strike must give skew ~0. A non-zero result
        would mean the skew is measuring the solver, not the market."""
        f = day_features(fo_frame(vol=0.25), ["RELIANCE"])
        assert abs(f.at["RELIANCE", "iv_skew"]) < 0.01

    def test_term_structure_sign(self):
        f = day_features(fo_frame(vol=0.20, next_vol=0.30), ["RELIANCE"])
        assert f.at["RELIANCE", "iv_term"] == pytest.approx(0.10, abs=0.02)

    def test_pcr_is_log_and_signed_correctly(self):
        """More put OI than call OI must read positive."""
        f = day_features(fo_frame(call_oi=1000, put_oi=2000), ["RELIANCE"])
        assert f.at["RELIANCE", "pcr_oi"] == pytest.approx(np.log(2.0), abs=1e-6)
        f2 = day_features(fo_frame(call_oi=2000, put_oi=1000), ["RELIANCE"])
        assert f2.at["RELIANCE", "pcr_oi"] < 0

    def test_balanced_book_is_zero_not_one(self):
        f = day_features(fo_frame(call_oi=1500, put_oi=1500), ["RELIANCE"])
        assert f.at["RELIANCE", "pcr_oi"] == pytest.approx(0.0, abs=1e-9)

    def test_basis_is_annualised(self):
        """5 days to expiry, 0.2% rich -> ~14.6% annualised."""
        f = day_features(fo_frame(spot=1000.0, fut_px=1002.0), ["RELIANCE"])
        days = (NEAR - TRAD).days
        assert f.at["RELIANCE", "basis_annualised"] == pytest.approx(
            0.002 * 365.0 / days, rel=0.02)

    def test_oi_change_is_normalised(self):
        f = day_features(fo_frame(fut_oi=5000, doi=500), ["RELIANCE"])
        assert f.at["RELIANCE", "oi_change_norm"] == pytest.approx(0.1)

    def test_missing_symbol_yields_nan_not_zero(self):
        """Zero is a real reading for these features - balanced PCR, flat
        basis. A missing symbol must be absent, or the GA will treat 'no
        derivatives listed' as 'perfectly balanced positioning'."""
        f = day_features(fo_frame(), ["RELIANCE", "NOTLISTED"])
        assert f.loc["NOTLISTED"].isna().all()

    def test_every_declared_feature_is_produced(self):
        f = day_features(fo_frame(), ["RELIANCE"])
        assert list(f.columns) == list(FEATURE_NAMES)
        assert f.loc["RELIANCE"].notna().all(), f.loc["RELIANCE"]

    def test_empty_frame_is_handled(self):
        f = day_features(pd.DataFrame(), ["RELIANCE"])
        assert len(f) == 1 and f.isna().all().all()

    def test_index_instruments_are_included(self):
        """IDF/IDO are the index legs; excluding them would drop NIFTY."""
        df = fo_frame(symbol="NIFTY")
        df["FinInstrmTp"] = df["FinInstrmTp"].replace({"STF": "IDF", "STO": "IDO"})
        f = day_features(df, ["NIFTY"])
        assert np.isfinite(f.at["NIFTY", "atm_iv"])


class TestParsing:
    def test_bad_zip_returns_none_not_an_exception(self):
        assert parse_fo(b"not a zip") is None

    def test_causality_note_is_honoured_by_the_schema(self):
        """TradDt must be present - the whole causal argument is that
        day T's file describes day T's close."""
        f = fo_frame()
        assert "TradDt" in f.columns and f["TradDt"].iloc[0] == TRAD
